### PR TITLE
Fix #52: Fix double checked locking when constructing SecureRandom

### LINKED ISSUE #52: Fix double checked locking when constructing SecureRandom
Currently, we use a code that may not work reliably. See discussion under #51.

### PR DESCRIPTION
**Pull request by romanstrobl**
I added the missing `volatile` keyword.

### CODE REVIEW

**Comment by kasahiti** [comment]
Suggestion : use a localSecureRandom in the method, as described [here](https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java). It seems that doing so may "improve the method's overall performance by as much as 40 percent." (in the case where secureRandom is already initialized).

**Comment by romanstrobl** [comment]
Thank you for the nice suggestion. I will run a benchmark to confirm the performance improvement.

**Comment by petrdvorak** [comment]
Hello @kasahiti, as described earlier - we need you to file our CLA: https://forms.gle/r715RoVDoji4GD7K7

Without it, we are unable to accept any contributions from you. While you remain the author of the change, we need you to transfer the usage right to us so that we can freely work with the software (for example, change the license later to any license we need, or use the software in our commercial software without asking your permission, etc.).

**Comment by romanstrobl** [comment]
I wrote a benchmark with 100 threads and 50 * 100 repetitions which calls the `generateRandomBytes` method in uninitialized state using original code and code with local reference. So the test switches between original code and code with local reference after 100 cycles to avoid fluctuations in load on the computer and repeats for 50 times. There are 500000 method calls total for each variant.

The result is:
```
Original code avg time: 62507771 nanoseconds
Code with local reference avg time: 61581294 nanoseconds
```

So there is a small improvement in the local reference variant. But given that the improvement is consistent (checked by repeating the whole benchmark several times), let's use the variant with local reference.

**Review by petrdvorak — APPROVED** [review]
Looks OK

**Pull request merged**
