### PR TITLE
Fix #54: private no-arg constructor to utility classes

### LINKED ISSUE #54: Add private non-arg constructor to classes that should not be instantiated directly
See the discussion under #51, i.e., `UnsignedLong`

### PR DESCRIPTION
**Pull request by kasahiti**
These classes should not be instantiated directly. An `IllegalStateException()` will be thrown in this case.

### CODE REVIEW

**Comment by romanstrobl** [comment]
I believe there is no need to throw exceptions in private constructors. If the constructor is private, it cannot be called. Empty implementation of the private constructors should be sufficient. Or do you have any other reason to throw the exceptions?

**Comment by kasahiti** [comment]
@romanstrobl Private constructors can still be called within the class; it's only to prevent mistakes.

**Comment by romanstrobl** [comment]
How would you call a private constructor within a class? As far as I know, it is not possible unless you use the reflection API.

**Comment by kasahiti** [comment]
The most simple example I could imagine : 

```java
public class UtilClass {

    private UtilClass() {
        throw new IllegalStateException("Utility class");
    }

    public void someMethod() {
        UtilClass utilClass = new UtilClass();
    }

}
```
It's perfectly possible to instantiate a class with private constructor within the same class. The `IllegalStateException` raised in the constructor aims to prevent this.

**Comment by petrdvorak** [comment]
@kasahiti We are trying to avoid unnecessarily code for trivial tasks. This particular change is from the category "meh, maybe yes but not really needed". The programmer who would call the constructor inside the same class is already in that class and can change anything (the comment "do not call" has the same benefit as the exception).

**Comment by romanstrobl** [comment]
@kasahiti So, you want to prevent someone to call a private constructor on a utility class? Why would anyone do this?

**Comment by petrdvorak** [comment]
Hello @kasahiti, as described earlier - we need you to file our CLA: https://forms.gle/r715RoVDoji4GD7K7

Without it, we are unable to accept any contributions from you. While you remain the author of the change, we need you to transfer the usage right to us so that we can freely work with the software (for example, change the license later to any license we need, or use the software in our commercial software without asking your permission, etc.).

**Comment by kasahiti** [comment]
@romanstrobl @petrdvorak It is considered best practice to prevent others from doing "crazy" things; just like instanciating a public class with a private constructor, but as you're considering it uncessarry, I changed my commit.

**Comment by kasahiti** [comment]
> Hello @kasahiti, as described earlier - we need you to file our CLA: https://forms.gle/r715RoVDoji4GD7K7
> 
> Without it, we are unable to accept any contributions from you. While you remain the author of the change, we need you to transfer the usage right to us so that we can freely work with the software (for example, change the license later to any license we need, or use the software in our commercial software without asking your permission, etc.).

I'm filling it right now.

**Review by petrdvorak — APPROVED** [review]
Looks OK

**Pull request merged**
